fix: remove kapt libs.retrofit - Retrofit does not have annotation processor
- Retrofit annotations (@GET, @POST, etc.) are regular Java annotations
- They should be available via 'implementation libs.retrofit' dependency
- 'kapt libs.retrofit' was incorrectly treating Retrofit as annotation processor
- This was causing KAPT to fail during stub generation
- Error: 'incompatible types: Object cannot be converted to Annotation'